/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author DANG
 */
public class LoginView extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    public JTextField txtUsername;
    public JPasswordField txtPassword;
    public JButton btnLogin;

    public LoginView() {

        setTitle("LE CHÂTEAU DORÉ - LOGIN");
        setSize(500, 420);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // ===== COLOR THEME =====
        Color gold = new Color(212, 175, 55);
        Color darkBrown = new Color(30, 20, 10);
        Color softWhite = new Color(245, 240, 230);

        // ===== MAIN PANEL =====
        JPanel mainPanel = new JPanel();
        mainPanel.setBackground(darkBrown);
        mainPanel.setLayout(null);

        // ===== TITLE =====
        JLabel lblTitle = new JLabel("LE CHÂTEAU DORÉ", SwingConstants.CENTER);
        lblTitle.setBounds(50, 30, 400, 40);
        lblTitle.setForeground(gold);
        lblTitle.setFont(new Font("Serif", Font.BOLD, 28));
        mainPanel.add(lblTitle);

        JLabel lblSub = new JLabel("Fine European Cuisine Management System", SwingConstants.CENTER);
        lblSub.setBounds(50, 65, 400, 25);
        lblSub.setForeground(softWhite);
        lblSub.setFont(new Font("SansSerif", Font.PLAIN, 13));
        mainPanel.add(lblSub);

        // ===== USERNAME =====
        JLabel lblUser = new JLabel("Username");
        lblUser.setBounds(100, 120, 300, 20);
        lblUser.setForeground(gold);
        lblUser.setFont(new Font("SansSerif", Font.BOLD, 14));
        mainPanel.add(lblUser);

        txtUsername = new JTextField();
        txtUsername.setBounds(100, 145, 300, 35);
        styleTextField(txtUsername, gold);
        mainPanel.add(txtUsername);

        // ===== PASSWORD =====
        JLabel lblPass = new JLabel("Password");
        lblPass.setBounds(100, 190, 300, 20);
        lblPass.setForeground(gold);
        lblPass.setFont(new Font("SansSerif", Font.BOLD, 14));
        mainPanel.add(lblPass);

        txtPassword = new JPasswordField();
        txtPassword.setBounds(100, 215, 300, 35);
        styleTextField(txtPassword, gold);
        mainPanel.add(txtPassword);

        // ===== LOGIN BUTTON =====
        btnLogin = new JButton("LOGIN");
        btnLogin.setBounds(175, 270, 150, 40);
        styleButton(btnLogin, gold);
        mainPanel.add(btnLogin);

        add(mainPanel, BorderLayout.CENTER);
    }

    private void styleTextField(JTextField field, Color gold) {
        field.setBackground(new Color(60, 40, 20));
        field.setForeground(Color.WHITE);
        field.setCaretColor(Color.WHITE);
        field.setBorder(BorderFactory.createLineBorder(gold, 1));
        field.setFont(new Font("SansSerif", Font.PLAIN, 14));
    }

    private void styleButton(JButton button, Color gold) {
        button.setFocusPainted(false);
        button.setBackground(new Color(60, 40, 20));
        button.setForeground(gold);
        button.setFont(new Font("SansSerif", Font.BOLD, 16));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setBorder(BorderFactory.createLineBorder(gold, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
